### PR TITLE
Update Continuous Integration

### PR DESCRIPTION
**Pull request by mseng10**
### Description
This PR will essentially update the CI with the recent release of ITK `v5.1.2`

#### Changes 
- Bumping ITK versions from `5.1.1` to `5.1.2` in: 
      - `setup.py`
      - `build-test-package.yml`
- Removing already disabled CI, as the new GitHub Actions have been recently integrated
      - Appveyor
      - Travis
      - CircleCI

### CODE REVIEW

**Comment by thewtex** [comment]
@mseng10 could the recent updates from ITKModuleTemplate to address the macOS 10.15 issue please be added?

**Comment by mseng10** [comment]
@thewtex I think for this module and the rest of the remote modules it would be best to update them all with the up-to date version of the `ITKModuleTemplate`. For modules with an open PR such as this one I will just push the changes on-top of these, while for modules with no open PRs, I'll just create a new PR.

**Comment by mseng10** [comment]
@thewtex The recent changes have been implemented.

**Review by thewtex — APPROVED** [review]
@mseng10 thank you!

**Pull request merged**
